// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job_Type int32

const (
	Job_DOWNLOAD        Job_Type = 0
	Job_CALCULATE_STATS Job_Type = 1
	Job_GET_REVIEWS     Job_Type = 2
)

var Job_Type_name = map[int32]string{
	0: "DOWNLOAD",
	1: "CALCULATE_STATS",
	2: "GET_REVIEWS",
}

var Job_Type_value = map[string]int32{
	"DOWNLOAD":        0,
	"CALCULATE_STATS": 1,
	"GET_REVIEWS":     2,
}

func (x Job_Type) String() string {
	return proto.EnumName(Job_Type_name, int32(x))
}

func (Job_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{9, 0}
}

type AddBookRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (m *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(m, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AddBookResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (m *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(m, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookResponse struct {
	Book                 *Book         `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Stats                *BookStats    `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Reviews              []*BookReview `protobuf:"bytes,3,rep,name=reviews,proto3" json:"reviews,omitempty"`
	JobStatus            []string      `protobuf:"bytes,4,rep,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *GetBookResponse) GetStats() *BookStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *GetBookResponse) GetReviews() []*BookReview {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *GetBookResponse) GetJobStatus() []string {
	if m != nil {
		return m.JobStatus
	}
	return nil
}

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{6}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type BookStats struct {
	NumberOfWords        int64    `protobuf:"varint,1,opt,name=number_of_words,json=numberOfWords,proto3" json:"number_of_words,omitempty"`
	LongestWord          string   `protobuf:"bytes,2,opt,name=longest_word,json=longestWord,proto3" json:"longest_word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookStats) Reset()         { *m = BookStats{} }
func (m *BookStats) String() string { return proto.CompactTextString(m) }
func (*BookStats) ProtoMessage()    {}
func (*BookStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{7}
}

func (m *BookStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookStats.Unmarshal(m, b)
}
func (m *BookStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookStats.Marshal(b, m, deterministic)
}
func (m *BookStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookStats.Merge(m, src)
}
func (m *BookStats) XXX_Size() int {
	return xxx_messageInfo_BookStats.Size(m)
}
func (m *BookStats) XXX_DiscardUnknown() {
	xxx_messageInfo_BookStats.DiscardUnknown(m)
}

var xxx_messageInfo_BookStats proto.InternalMessageInfo

func (m *BookStats) GetNumberOfWords() int64 {
	if m != nil {
		return m.NumberOfWords
	}
	return 0
}

func (m *BookStats) GetLongestWord() string {
	if m != nil {
		return m.LongestWord
	}
	return ""
}

type BookReview struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Review               string   `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookReview) Reset()         { *m = BookReview{} }
func (m *BookReview) String() string { return proto.CompactTextString(m) }
func (*BookReview) ProtoMessage()    {}
func (*BookReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{8}
}

func (m *BookReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookReview.Unmarshal(m, b)
}
func (m *BookReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookReview.Marshal(b, m, deterministic)
}
func (m *BookReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookReview.Merge(m, src)
}
func (m *BookReview) XXX_Size() int {
	return xxx_messageInfo_BookReview.Size(m)
}
func (m *BookReview) XXX_DiscardUnknown() {
	xxx_messageInfo_BookReview.DiscardUnknown(m)
}

var xxx_messageInfo_BookReview proto.InternalMessageInfo

func (m *BookReview) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BookReview) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type Job struct {
	Metadata             map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 Job_Type          `protobuf:"varint,2,opt,name=type,proto3,enum=Job_Type" json:"type,omitempty"`
	Book                 *Book             `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{9}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Job) GetType() Job_Type {
	if m != nil {
		return m.Type
	}
	return Job_DOWNLOAD
}

func (m *Job) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func init() {
	proto.RegisterEnum("Job_Type", Job_Type_name, Job_Type_value)
	proto.RegisterType((*AddBookRequest)(nil), "AddBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "AddBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "GetBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "ListBooksResponse")
	proto.RegisterType((*Book)(nil), "Book")
	proto.RegisterType((*BookStats)(nil), "BookStats")
	proto.RegisterType((*BookReview)(nil), "BookReview")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterMapType((map[string]string)(nil), "Job.MetadataEntry")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x14, 0xac, 0x3f, 0x48, 0xe2, 0xe7, 0x04, 0x3b, 0xaf, 0x55, 0xe5, 0x52, 0x45, 0x22, 0x96, 0x5a,
	0x71, 0x88, 0x56, 0x15, 0xbd, 0x54, 0xe9, 0xa5, 0x90, 0xa0, 0xa8, 0x11, 0x2d, 0x92, 0xa1, 0x41,
	0xea, 0x05, 0xd9, 0xf5, 0x86, 0x12, 0xc0, 0x4b, 0xbd, 0xeb, 0x44, 0xfc, 0x8f, 0x5e, 0xfb, 0xff,
	0xfa, 0x33, 0xaa, 0x5d, 0x2f, 0x6e, 0x20, 0x37, 0xde, 0xbc, 0xf1, 0xdb, 0x61, 0x34, 0x03, 0x90,
	0x30, 0x36, 0x27, 0xab, 0x9c, 0x09, 0x16, 0x86, 0x50, 0xef, 0xa4, 0x69, 0x97, 0xb1, 0x79, 0x44,
	0x7f, 0x15, 0x94, 0x0b, 0xf4, 0xc1, 0x2a, 0xf2, 0x45, 0x60, 0x34, 0x8d, 0x96, 0x13, 0xc9, 0x9f,
	0xe1, 0x29, 0x78, 0x15, 0x87, 0xaf, 0x58, 0xc6, 0x29, 0xd6, 0xc1, 0x9c, 0xa5, 0x8a, 0x63, 0x45,
	0xe6, 0x2c, 0x0d, 0x9b, 0x50, 0xbf, 0xa2, 0xe2, 0xf1, 0x99, 0x5d, 0xc6, 0x6f, 0x03, 0xbc, 0x8a,
	0xa2, 0xaf, 0xbc, 0x02, 0x5b, 0x4a, 0x51, 0x2c, 0xb7, 0x5d, 0x23, 0x6a, 0xa9, 0x20, 0x6c, 0x42,
	0x8d, 0x8b, 0x58, 0xf0, 0xc0, 0x54, 0x3b, 0x50, 0xbb, 0xa1, 0x44, 0xa2, 0x72, 0x81, 0x6f, 0x60,
	0x3f, 0xa7, 0xf7, 0x33, 0xfa, 0xc0, 0x03, 0xab, 0x69, 0xb5, 0xdc, 0xb6, 0x5b, 0x7e, 0xaf, 0xb0,
	0x68, 0xb3, 0xc3, 0x13, 0x80, 0x3b, 0x96, 0x4c, 0xe4, 0x37, 0x05, 0x0f, 0xec, 0xa6, 0xd5, 0x72,
	0x22, 0xe7, 0x8e, 0x25, 0x43, 0x05, 0x84, 0x08, 0x7e, 0x7f, 0xc6, 0x95, 0x2c, 0xae, 0xa5, 0x87,
	0xef, 0xe0, 0xf8, 0x11, 0xa6, 0xb5, 0xbe, 0x86, 0x9a, 0x14, 0xc6, 0x03, 0x43, 0x3d, 0xa6, 0xc5,
	0x96, 0x58, 0x98, 0x83, 0x2d, 0xc7, 0xdd, 0x3f, 0xbd, 0xf1, 0xd2, 0xac, 0xbc, 0xc4, 0x17, 0x50,
	0x13, 0x33, 0xb1, 0xa0, 0x81, 0xa5, 0xb0, 0x72, 0xc0, 0x97, 0xb0, 0x17, 0x17, 0xe2, 0x27, 0xcb,
	0x03, 0x5b, 0xc1, 0x7a, 0xc2, 0x06, 0x1c, 0x2c, 0xe2, 0x6c, 0x5a, 0xc4, 0x53, 0x1a, 0xd4, 0xd4,
	0xa6, 0x9a, 0xc3, 0x1b, 0x70, 0x2a, 0x4f, 0xf0, 0x2d, 0x78, 0x59, 0xb1, 0x4c, 0x68, 0x3e, 0x61,
	0xb7, 0x93, 0x07, 0x96, 0xa7, 0x5c, 0xab, 0x38, 0x2a, 0xe1, 0xc1, 0xed, 0x58, 0x82, 0x78, 0x0a,
	0x87, 0x0b, 0x96, 0x4d, 0x29, 0x17, 0x8a, 0xa5, 0x95, 0xb9, 0x1a, 0x93, 0x9c, 0xf0, 0x13, 0xc0,
	0x7f, 0x1f, 0xa5, 0x82, 0x82, 0xd3, 0x3c, 0x8b, 0x97, 0x54, 0x47, 0xa2, 0x9a, 0xa5, 0xea, 0xd2,
	0x65, 0x7d, 0x46, 0x4f, 0xe1, 0x5f, 0x03, 0xac, 0x6b, 0x96, 0x20, 0x81, 0x83, 0x25, 0x15, 0x71,
	0x1a, 0x8b, 0x58, 0xbb, 0x86, 0xe4, 0x9a, 0x25, 0xe4, 0x8b, 0x06, 0x7b, 0x99, 0xc8, 0xd7, 0x51,
	0xc5, 0xc1, 0x13, 0xb0, 0xc5, 0x7a, 0x45, 0xd5, 0xb5, 0x7a, 0xdb, 0x51, 0xdc, 0xd1, 0x7a, 0x45,
	0x23, 0x05, 0x57, 0x69, 0xb1, 0x9e, 0xa4, 0xa5, 0xf1, 0x11, 0x8e, 0xb6, 0x8e, 0x4a, 0xe3, 0xe7,
	0x74, 0xbd, 0x09, 0xf1, 0x9c, 0xae, 0xa5, 0xf1, 0xf7, 0xf1, 0xa2, 0xa0, 0x5a, 0x6b, 0x39, 0x9c,
	0x9b, 0x1f, 0x8c, 0xf0, 0x1c, 0x6c, 0xf9, 0x0a, 0x1e, 0xc2, 0xc1, 0xe5, 0x60, 0xfc, 0xb5, 0x3f,
	0xe8, 0x5c, 0xfa, 0xcf, 0xf0, 0x39, 0x78, 0x17, 0x9d, 0xfe, 0xc5, 0xb7, 0x7e, 0x67, 0xd4, 0x9b,
	0x0c, 0x47, 0x9d, 0xd1, 0xd0, 0x37, 0xd0, 0x03, 0xf7, 0xaa, 0x37, 0x9a, 0x44, 0xbd, 0x9b, 0xcf,
	0xbd, 0xf1, 0xd0, 0x37, 0xdb, 0x7f, 0x0c, 0x70, 0xa5, 0x8e, 0x6e, 0xfc, 0x63, 0x4e, 0xb3, 0x14,
	0xcf, 0x60, 0x5f, 0x57, 0x05, 0x3d, 0xb2, 0x5d, 0xac, 0x86, 0x4f, 0x76, 0x5b, 0x74, 0x06, 0xfb,
	0xba, 0x12, 0xe8, 0x91, 0xed, 0xfe, 0x34, 0x7c, 0xb2, 0xdb, 0x96, 0x36, 0x38, 0x55, 0x2c, 0xf1,
	0x98, 0xec, 0xc6, 0xb6, 0x81, 0xe4, 0x49, 0x6a, 0xbb, 0xf6, 0x77, 0x73, 0x95, 0x24, 0x7b, 0xaa,
	0xeb, 0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x93, 0xc0, 0x6f, 0xf9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookBackendClient is the client API for BookBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookBackendClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
}

type bookBackendClient struct {
	cc *grpc.ClientConn
}

func NewBookBackendClient(cc *grpc.ClientConn) BookBackendClient {
	return &bookBackendClient{cc}
}

func (c *bookBackendClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, "/BookBackend/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookBackendClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/BookBackend/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookBackendClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/BookBackend/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookBackendServer is the server API for BookBackend service.
type BookBackendServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
}

func RegisterBookBackendServer(s *grpc.Server, srv BookBackendServer) {
	s.RegisterService(&_BookBackend_serviceDesc, srv)
}

func _BookBackend_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookBackend_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookBackend_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BookBackend",
	HandlerType: (*BookBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookBackend_AddBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookBackend_GetBook_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _BookBackend_ListBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
